### ISSUE TITLE
workWith function

### ISSUE THREAD

**Issue by ddispaltro** [actorapp/actor-platform#125]
I was going over the code and was curious specifically what you had in mind with the design of `workWith`[1] as I haven't seen this pattern before.  Wouldn't messages that come in between when the function runs and when the `Work` message is received observe the old state? Is that by design?

[1] https://github.com/actorapp/actor-platform/blob/99413fc8e611a797417c28b6e86247a55d71cb93/actor-server/actor-core/src/main/scala/im/actor/server/office/Processor.scala#L49

**Comment by prettynatty** [comment]
It is a deprecated function which in its current state is as a work-around for an old bug in our code, and it could tolerate such behavior because messages between sending of `Work` and receiving it were being stashed.
Right now workWith should be rewritten back to its normal behavior, @ddispaltro thanks for spotting the issue. Again :) We appreciate attention to our server-side code.

Actually `Processor` was our experiment to implement CQRS on top of Akka Sharding and Akka Persistence. It did not succeed because we found weird bugs in PersistentView, so we decided that we could live with "Q" part just in trait mixed in Actor responsible for "C" for a while, until Akka 2.4 release and our migration to it: Akka 2.4 has huge Persistence improvements of a Query side, we are looking forward to find time to implement real CQRS.

**Comment by ddispaltro** [comment]
Got it makes sense, since it was used directly in the Group processor, without persistStashingReply or any of those methods, I thought I was missing something. 

Yeah 2.4 PQ stuff is great, most journals don't support the PQ yet though.

Thanks for answering my questions!
